name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Swift
        uses: swift-actions/setup-swift@v1
        with:
          swift-version: '6.1'

      - name: Swift format (lint)
        run: swift format --lint --recursive .

      - name: Build
        run: swift build --build-tests

      - name: Test
        run: swift test
